cdversion: '3.1'
services:
  postgres:
    image: postgres:latest
    container_name: desi-meals-abroad-postgres
    environment:
      POSTGRES_DB: dma-db
      POSTGRES_USER: dma-admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
